/* eslint-disable */
/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs');
const { join } = require('path');

const { platform, arch } = process;

let nativeBinding = null;
let localFileExisted = false;
let loadError = null;

function isMusl() {
  // For Node 12+, use report to detect musl
  if (
    typeof process.report !== 'undefined' &&
    typeof process.report.getReport === 'function'
  ) {
    const report =
      typeof process.report.getReport === 'function'
        ? process.report.getReport()
        : null;
    if (report) {
      const header =
        typeof report === 'string' ? JSON.parse(report).header : report.header;
      if (header && header.glibcVersionRuntime) {
        return false;
      }
    }
  }
  try {
    const output = readFileSync('/usr/bin/ldd', 'utf8');
    return output.includes('musl');
  } catch {
    return true;
  }
}

switch (platform) {
  case 'darwin':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'swiftllm.darwin-x64.node')
        );
        try {
          if (localFileExisted) {
            nativeBinding = require('./swiftllm.darwin-x64.node');
          } else {
            nativeBinding = require('swiftllm-darwin-x64');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'swiftllm.darwin-arm64.node')
        );
        try {
          if (localFileExisted) {
            nativeBinding = require('./swiftllm.darwin-arm64.node');
          } else {
            nativeBinding = require('swiftllm-darwin-arm64');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`);
    }
    break;
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'swiftllm.linux-x64-musl.node')
          );
          try {
            if (localFileExisted) {
              nativeBinding = require('./swiftllm.linux-x64-musl.node');
            } else {
              nativeBinding = require('swiftllm-linux-x64-musl');
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'swiftllm.linux-x64-gnu.node')
          );
          try {
            if (localFileExisted) {
              nativeBinding = require('./swiftllm.linux-x64-gnu.node');
            } else {
              nativeBinding = require('swiftllm-linux-x64-gnu');
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'swiftllm.linux-arm64-musl.node')
          );
          try {
            if (localFileExisted) {
              nativeBinding = require('./swiftllm.linux-arm64-musl.node');
            } else {
              nativeBinding = require('swiftllm-linux-arm64-musl');
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'swiftllm.linux-arm64-gnu.node')
          );
          try {
            if (localFileExisted) {
              nativeBinding = require('./swiftllm.linux-arm64-gnu.node');
            } else {
              nativeBinding = require('swiftllm-linux-arm64-gnu');
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`);
    }
    break;
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'swiftllm.win32-x64-msvc.node')
        );
        try {
          if (localFileExisted) {
            nativeBinding = require('./swiftllm.win32-x64-msvc.node');
          } else {
            nativeBinding = require('swiftllm-win32-x64-msvc');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'swiftllm.win32-arm64-msvc.node')
        );
        try {
          if (localFileExisted) {
            nativeBinding = require('./swiftllm.win32-arm64-msvc.node');
          } else {
            nativeBinding = require('swiftllm-win32-arm64-msvc');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`);
    }
    break;
  default:
    throw new Error(
      `Unsupported OS: ${platform}, architecture: ${arch}`
    );
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError;
  }
  throw new Error('Failed to load native binding');
}

const { SwiftLLM, completion, asyncCompletion } = nativeBinding;

module.exports.SwiftLLM = SwiftLLM;
module.exports.completion = completion;
module.exports.asyncCompletion = asyncCompletion;
