/* auto-generated by NAPI-RS */

/** A chat message. */
export interface Message {
  role: string;
  content?: string | null;
  name?: string | null;
  toolCallId?: string | null;
}

/** Token usage statistics. */
export interface Usage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
}

/** A tool call returned by the model. */
export interface ToolCall {
  id: string;
  functionName: string;
  functionArguments: string;
}

/** Response from a chat completion call. */
export interface CompletionResponse {
  /** Unique response identifier. */
  id: string;
  /** Model that generated the response. */
  model: string;
  /** The generated text content. */
  content?: string | null;
  /** Why the model stopped generating (e.g. "stop", "length"). */
  finishReason?: string | null;
  /** Token usage statistics. */
  usage?: Usage | null;
  /** Tool calls requested by the model. */
  toolCalls?: ToolCall[] | null;
  /** The full raw JSON response as a string. */
  raw: string;
}

/** Options for a completion request. */
export interface CompletionOptions {
  /** Sampling temperature (0-2). */
  temperature?: number | null;
  /** Maximum tokens to generate. */
  maxTokens?: number | null;
  /** Nucleus sampling threshold. */
  topP?: number | null;
  /** Override the provider API key for this request. */
  apiKey?: string | null;
  /** Override the base URL for this request. */
  baseUrl?: string | null;
}

/** Options when adding a provider. */
export interface ProviderOptions {
  /** Custom base URL for the provider API. */
  baseUrl?: string | null;
  /** Explicit list of model names supported by this provider. */
  models?: string[] | null;
}

/**
 * The main SwiftLLM client for Node.js.
 *
 * @example
 * ```ts
 * import { SwiftLLM } from 'swiftllm';
 *
 * const llm = new SwiftLLM();
 * llm.addProvider('openai', 'sk-...');
 * const resp = await llm.completion('gpt-4o-mini', 'Hello!');
 * console.log(resp.content);
 * ```
 */
export class SwiftLLM {
  /** Create a new SwiftLLM instance. */
  constructor();

  /**
   * Register a provider with its API key.
   *
   * @param name - Provider name: "openai", "anthropic", "gemini", or "mistral"
   * @param apiKey - The provider's API key
   * @param options - Optional configuration (baseUrl, models)
   */
  addProvider(name: string, apiKey: string, options?: ProviderOptions): void;

  /** List registered provider names. */
  listProviders(): string[];

  /**
   * Send an async chat completion request.
   *
   * @param model - Model identifier (e.g. "gpt-4o-mini", "claude-sonnet-4-20250514")
   * @param prompt - A string or array of Message objects
   * @param options - Optional parameters (temperature, maxTokens, etc.)
   * @returns A Promise that resolves to a CompletionResponse
   */
  completion(
    model: string,
    prompt: string | Message[],
    options?: CompletionOptions,
  ): Promise<CompletionResponse>;
}

/**
 * Synchronous one-shot completion — infers the provider from the model name.
 *
 * @param model - Model identifier (e.g. "gpt-4o-mini")
 * @param prompt - A string or array of Message objects
 * @param options - Options including apiKey (required)
 * @returns CompletionResponse
 *
 * @example
 * ```ts
 * import { completion } from 'swiftllm';
 *
 * const resp = completion('gpt-4o-mini', 'Hello!', { apiKey: 'sk-...' });
 * console.log(resp.content);
 * ```
 */
export function completion(
  model: string,
  prompt: string | Message[],
  options?: CompletionOptions,
): CompletionResponse;

/**
 * Async one-shot completion — infers the provider from the model name.
 *
 * @param model - Model identifier (e.g. "gpt-4o-mini")
 * @param prompt - A string or array of Message objects
 * @param options - Options including apiKey (required)
 * @returns A Promise that resolves to a CompletionResponse
 *
 * @example
 * ```ts
 * import { asyncCompletion } from 'swiftllm';
 *
 * const resp = await asyncCompletion('gpt-4o-mini', 'Hello!', { apiKey: 'sk-...' });
 * console.log(resp.content);
 * ```
 */
export function asyncCompletion(
  model: string,
  prompt: string | Message[],
  options?: CompletionOptions,
): Promise<CompletionResponse>;
